### ISSUE TITLE
IsContributor not working properly

### ISSUE THREAD

**Issue by jimmyhiggs337** [FoxxMD/reddit-context-bot#142]
config:
```
runs:
  -checks:
        - name: approveUser
          description: approved posts from approved users
          kind: submission
          rules:
             - name: approveContrib
               kind: author
               authorIs: 
                   - isContributor: true
          actions:
           - kind: approve
```
           

- **Expected behavior:** Only users who have been approved by the subeddit have their posts approved

- **Actual behavior:** ALL posts on the subreddit are approved
